project:
  type: website
  output-dir: docs

website:
  title: "Jiang Lab"
  site-url: "https://yjianglab.github.io/yjianglabcn/"
  navbar:
    left:
      - href: index.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: team.qmd
        text: Team
      - href: join.qmd
        text: Join the Lab

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true





