---
title: "Join the Lab"
---

## Postdoctoral Fellows

We are recruiting highly motivated postdoctoral fellows in two broad areas:
<br> (1) **Synthetic Biology & Protein Engineering**: translational synthetic biology, protein and antibody engineering, therapeutic protein design, antibody-drug conjugates (ADCs), genetic & cellular engineering, immunoengineering, and related areas.
<br> (2) **Nanomedicine & Gene Delivery**: nanoparticle engineering, targeted drug delivery, nucleic acid therapeutics, CRISPR technologies, radiotherapy, and related areas.
<br> Successful candidates will have a strong publication record, creativity, and enthusiasm for interdisciplinary research. Fellows will have the opportunity to lead independent projects in a collaborative and supportive environment while working at the interface of engineering, biology, and medicine.
<br> If interested, please email Yuyan (<u>yyjiang@stanford.edu</u>) with a CV, cover letter, and contact information of at least three references.

## Graduate Students
We'll accept graduate students from the [University of Washington Molecular and Cellular Biology (MCB) program](https://mcb-seattle.edu/). Interested students are encouraged to email Yuyan (<u>yyjiang@stanford.edu</u>) with their CV to discuss a potential lab rotation and research projects.

## Research Technicians
We are recruiting research technicians to support projects in chemical biology and therapeutic development. Preferred qualifications include experience with mammalian cell culture, PCR/qPCR, molecular cloning, Western blotting, ELISA, flow cytometry, fluorescence microscopy, DNA/RNA extraction, protein expression and purification, and related molecular and cellular biology techniques. Experience with mouse studies, immunology assays, or protein characterization is a plus.
<br> This position is ideal for individuals considering graduate or medical school. Technicians will receive close mentorship, opportunities for scientific and professional development, and may earn authorship on publications through their research contributions.
<br> If interested, please email Yuyan (<u>yyjiang@stanford.edu</u>) with a CV and a brief statement of interest. Contact information for references is optional but recommended.

## Post-Baccalaureate Scholars
We welcome post-baccalaureate trainees through the [Fred Hutch Postbaccalaureate Scholar Program](https://www.fredhutch.org/en/education-training/fred-hutch-postbaccalaureate-scholar-program.html). Interested candidates are encouraged to apply through the program website.

## Undergraduate Students
We'll accept undergraduate students through the University of Washington. Interested students are encouraged to email Yuyan (<u>yyjiang@stanford.edu</u>) with their CV and a brief description of their research interests. We also welcome students through the [Fred Hutchinson Summer Undergraduate Research Program (SURP)](https://www.fredhutch.org/en/education-training/undergraduate-students/summer-undergraduate-research-program.html). 


