---
title: "Publications"
---

## 2026
1.	Zhu, L., He, F., Deng, W., Zhou, Y., **Jiang, Y.**, Du, X., & Huang, J. (2026). Urinary fluorogenic reporters for noninvasive detection and staging of kidney fibrosis. Science Translational Medicine, 18(850), eadz6929.
2.	Yang, X., Liang, B., Fu, L., Deng, W., **Jiang, Y.**, Xu, W., Chen, J., Zhou, Y., Wu, K., & Huang, J. (2026). Bioorthogonal fluorogenic reporters for noninvasive imaging and urinalysis of immunotherapeutic response in renal cell carcinoma. Advanced Science, e24298.
3.	Wu, M., Chen, W., Qu, R., Zheng, L., Tan, W., Tang, J., Li, S., Li, H., Chen, L., Zhou, W., Liu, Y., Huo, D., **Jiang, Y.#**, Jiang, X.#, & Zhen, X.# (2026). Sonodynamic/mechano-induced cGAMP biosynthesis enables in situ STING activation for enhanced cancer immunotherapy. Advanced Functional Materials, e24298. (# Co-corresponding author)

## 2025
4.	**Jiang, Y.**, Cao, H., Deng, H., Guan, L., Langthasa, J., Colburg, D. R., Melemenidis, S., Cotton, R. M., Aleman, J., Wang, X. J., Graves, E. E., Kalbasi, A., Pu, K., Rao, J., & Le, Q. T. (2025). Gold–siRNA supraclusters enhance the anti-tumor immune response of stereotactic ablative radiotherapy at primary and metastatic tumors. Nature Biotechnology, 43, 1496–1509.
5.	Ruan, B., Deng, W., Che, J., Yi, S., Liu, J., Xu, W., **Jiang, Y.**, Zhou, Y., Xie, P., Zhang, H., Zhao, H., & Huang, J. (2025). Unimolecular near-infrared chemiluminescent reporter for cascaded multiplex imaging of ischemia–reperfusion injury in the liver–kidney axis. Nature Communications, 16(1), 7743.
6.	Chen, L., Peng, M., Ouyang, Y., Chen, J., Li, H., Wu, M., Qu, R., Zhou, W., Zhang, C., **Jiang, Y.#**, Xu, S.#, Wu, W., Jiang, X.#, & Zhen, X.# (2025). Tuning second near-infrared fluorescence activation by regulating the excited-state charge transfer dynamics change ratio. Journal of the American Chemical Society, 147, 17330–17341. (# Co-corresponding author)
7.	Xu, W., Yi, S., Liu, J., **Jiang, Y.**, & Huang, J. (2025). Nitrile–aminothiol bioorthogonal near-infrared fluorogenic probes for ultrasensitive in vivo imaging. Nature Communications, 16(1), 8.
8.	Zhou, Y., Xu, W., Ruan, B., Zhu, L., **Jiang, Y.**, Cai, H., & Huang, J. (2025). Molecular imaging of renin activity using fluorogenic nanoprobes for precision antihypertensive therapy. Angewandte Chemie International Edition, 64, e202416002.

## 2024
9.	Guan, L., Viswanathan, V., **Jiang, Y.**, Vijayakumar, S., Cao, H., Zhao, J., Colburg, D. R., Neuhöfer, P., Zhang, Y., Wang, J., Xu, Y., Laseinde, E. E., Hildebrand, R., Rahman, M., Frock, R., Kong, C., Beachy, P. A., Artandi, S., & Le, Q. T. (2024). Tert-expressing cells contribute to salivary gland homeostasis and tissue regeneration after radiation therapy. Genes & Development, 38, 569–582.
10.	Liu, Y., Diao, S., Ruan, B., Zhou, Y., Yu, M., Dong, G., Xu, W., Ning, L., Zhou, W., **Jiang, Y.**, Xie, C., Fan, Q., & Huang, J. (2024). Molecular engineering of activatable NIR-II hemicyanine reporters for early diagnosis and prognostic assessment of inflammatory bowel disease. ACS Nano, 18(11), 8437–8451.

## 2023
11.	Ruan, B., Yu, M., Zhou, Y., Xu, W., Liu, Y., Liu, B., Zhu, L., Yi, S., **Jiang, Y.**, & Huang, J. (2023). Size-transformable superoxide-triggered nanoreporters for crosstalk-free dual fluorescence/chemiluminescence imaging and urinalysis in living mice. Angewandte Chemie International Edition, e202305812.
12.	Li, H., Zhou, S., Wu, M., Qu, R., Wang, X., Chen, W., **Jiang, Y.**, Jiang, X., & Zhen, X. (2023). Light-driven self-recruitment of biomimetic semiconducting polymer nanoparticles for precise tumor vascular disruption. Advanced Materials, e2210920.
13.	Xu, C., Huang, J., **Jiang, Y.**, He, S., Zhang, C., & Pu, K. (2023). Nanoparticles with ultrasound-induced afterglow luminescence for tumor-specific theranostics. Nature Biomedical Engineering, 7(3), 298–312.

## 2022
14.	Huang, J., Chen, X., **Jiang, Y.**, Zhang, C., He, S., Wang, H., & Pu, K. (2022). Renal clearable polyfluorophore nanosensors for early diagnosis of cancer and allograft rejection. Nature Materials, 21(5), 598–607.
15.	Wu, X.*, **Jiang, Y.***, Rommelfanger, N. J., Yang, F., Zhou, Q., Yin, R., Liu, J., Cai, S., Ren, W., Shin, A., Ong, K. S., Pu, K., & Hong, G. (2022). Tether-free photothermal deep-brain stimulation in freely behaving mice via wide-field illumination in the near-infrared-II window. Nature Biomedical Engineering, 6, 754–770. (* Co-first author)

## 2021
16.	**Jiang, Y.**, & Pu, K. (2021). Molecular probes for autofluorescence-free optical imaging. Chemical Reviews, 121(21), 13086–13131.
17.	Xu, C., **Jiang, Y.**, Huang, J., Huang, J., & Pu, K. (2021). Second near-infrared light-activatable polymeric nanoantagonist for photothermal immunometabolic cancer therapy. Advanced Materials, 33(36), e2101410.
18.	Zhang, C., Zeng, Z., Cui, D., He, S., **Jiang, Y.**, Li, J., Huang, J., & Pu, K. (2021). Semiconducting polymer nano-PROTACs for activatable photo-immunometabolic cancer therapy. Nature Communications, 12(1), 2934.
19.	Xu, C.*, **Jiang, Y.***, Han, Y., Pu, K., & Zhang, R. (2021). A polymer multicellular nanoengager for synergistic NIR-II photothermal immunotherapy. Advanced Materials, 33(14), e2008061. (* Co-first author)
20.	Huang, J.*, **Jiang, Y.***, Li, J., Huang, J., & Pu, K. (2021). Molecular chemiluminescent probes with a very long near-infrared emission wavelength for in vivo imaging. Angewandte Chemie International Edition, 60(8), 3999–4003. (* Co-first author)
21.	**Jiang, Y.**, Huang, J., Xu, C., & Pu, K. (2021). Activatable polymer nanoagonist for second near-infrared photothermal immunotherapy of cancer. Nature Communications, 12(1), 742.
22.	Li, J., Yu, X., **Jiang, Y.**, He, S., Zhang, Y., Luo, Y., & Pu, K. (2021). Second near-infrared photothermal semiconducting polymer nanoadjuvant for enhanced cancer immunotherapy. Advanced Materials, 33(4), e2003458.
23.	Zeng, Z., Zhang, C., Li, J., Cui, D., **Jiang, Y.**, & Pu, K. (2021). Activatable polymer nanoenzymes for photodynamic immunometabolic cancer therapy. Advanced Materials, 33(4), e2007247.

## Before 2021
24.	Dang, Q.*, **Jiang, Y.***, Wang, J., Wang, J., Zhang, Q., Zhang, M., Luo, S., Xie, Y., Pu, K., Li, Q., & Li, Z. (2020). Room-temperature phosphorescence resonance energy transfer for construction of near-infrared afterglow imaging agents. Advanced Materials, 32(52), e2006752. (* Co-first author)
25.	Huang, J., Huang, J., Cheng, P., **Jiang, Y.**, & Pu, K. (2020). Near-infrared chemiluminescent reporters for in vivo imaging of reactive oxygen and nitrogen species in kidneys. Advanced Functional Materials, 30(39), 2003628.
26.	He, S., **Jiang, Y.**, Li, J., & Pu, K. (2020). Semiconducting polycomplex nanoparticles for photothermal ferrotherapy of cancer. Angewandte Chemie International Edition, 59(26), 10633–10638.
27.	**Jiang, Y.**, Zhao, X., Huang, J., Li, J., Upputuri, P. K., Sun, H., Han, X., Pramanik, M., Miao, Y., Duan, H., Pu, K., & Zhang, R. (2020). Transformable hybrid semiconducting polymer nanozyme for second near-infrared photothermal ferrotherapy. Nature Communications, 11(1), 1857.
28.	Huang, J., **Jiang, Y.**, Li, J., He, S., Huang, J., & Pu, K. (2020). A renal-clearable macromolecular reporter for near-infrared fluorescence imaging of bladder cancer. Angewandte Chemie International Edition, 59(11), 4415–4420.
29.	Lyu, Y., He, S., Li, J., **Jiang, Y.**, Sun, H., Miao, Y., & Pu, K. (2019). A photolabile semiconducting polymer nanotransducer for near-infrared regulation of CRISPR/Cas9 gene editing. Angewandte Chemie International Edition, 58(50), 18197–18201.
30.	Huang, J., Lyu, Y., Li, J., Cheng, P., **Jiang, Y.**, & Pu, K. (2019). A renal-clearable duplex optical reporter for real-time imaging of contrast-induced acute kidney injury. Angewandte Chemie International Edition, 58(49), 17796–17804.
31.	Li, J., Cui, D., **Jiang, Y.**, Huang, J., Cheng, P., & Pu, K. (2019). Near-infrared photoactivatable semiconducting polymer nanoblockaders for metastasis-inhibited combination cancer therapy. Advanced Materials, 31(46), e1905091.
32.	Huang, J., Xie, C., Zhang, X., **Jiang, Y.**, Li, J., Fan, Q., & Pu, K. (2019). Renal-clearable molecular semiconductor for second near-infrared fluorescence imaging of kidney dysfunction. Angewandte Chemie International Edition, 58(42), 15120–15127.
33.	He, S., Xie, C., **Jiang, Y.**, & Pu, K. (2019). An organic afterglow protheranostic nanoassembly. Advanced Materials, 31(32), e1902672.
34.	Cui, D., Li, P., Zhen, X., Li, J., **Jiang, Y.**, Yu, A., Hu, X., & Pu, K. (2019). Thermoresponsive semiconducting polymer nanoparticles for contrast-enhanced photoacoustic imaging. Advanced Functional Materials, 29(38), 1903461.
35.	**Jiang, Y.**, Li, J., Zeng, Z., Xie, C., & Pu, K. (2019). Organic photodynamic nanoinhibitor for synergistic cancer therapy. Angewandte Chemie International Edition, 58(24), 8161–8165.
36.	Wang, Z., Zhen, X., Upputuri, P. K., **Jiang, Y.**, Lau, J., Pramanik, M., Pu, K., & Xing, B. (2019). Redox-activatable and acid-enhanced nanotheranostics for second near-infrared photoacoustic tomography and combined photothermal tumor therapy. ACS Nano, 13(5), 5816–5825.
37.	**Jiang, Y.**, Huang, J., Zhen, X., Zeng, Z., Li, J., Xie, C., Miao, Q., Chen, J., Chen, P., & Pu, K. (2019). A generic approach towards afterglow luminescent nanoparticles for ultrasensitive in vivo imaging. Nature Communications, 10(1), 2064.
38.	Cui, D., Huang, J., Zhen, X., Li, J., **Jiang, Y.**, & Pu, K. (2019). A semiconducting polymer nano-prodrug for hypoxia-activated photodynamic cancer therapy. Angewandte Chemie International Edition, 58(18), 5920–5924.
39.	Li, J., Huang, J., Lyu, Y., Huang, J., **Jiang, Y.**, Xie, C., & Pu, K. (2019). Photoactivatable organic semiconducting pro-nanoenzymes. Journal of the American Chemical Society, 141(9), 4073–4079.
40.	**Jiang, Y.**, Upputuri, P. K., Xie, C., Zeng, Z., Sharma, A., Zhen, X., Li, J., Huang, J., Pramanik, M., & Pu, K. (2019). Metabolizable semiconducting polymer nanoparticles for second near-infrared photoacoustic imaging. Advanced Materials, 31(11), e1808166.
41.	Wang, Z., Upputuri, P., Zhen, X., Zhang, R., **Jiang, Y.**, Ai, X., Zhang, Z., Hu, M., Meng, Z., Lu, Y., Zheng, Y., Pu, K., Pramanik, M., & Xing, B. (2019). pH-sensitive and biodegradable charge-transfer nanocomplex for second near-infrared photoacoustic tumor imaging. Nano Research, 12(1), 49–55.
42.	Li, J., Zhen, X., Lyu, Y., **Jiang, Y.**, Huang, J., & Pu, K. (2018). Cell membrane coated semiconducting polymer nanoparticles for enhanced multimodal cancer phototheranostics. ACS Nano, 12(8), 8520–8530.
43.	**Jiang, Y.**, & Pu, K. (2018). Multimodal biophotonics of semiconducting polymer nanoparticles. Accounts of Chemical Research, 51(8), 1840–1849.
44.	**Jiang, Y.**, & Pu, K. (2018). Molecular fluorescence and photoacoustic imaging in the second near-infrared optical window using organic contrast agents. Advanced Biosystems, 2(5), e1700262.
45.	Li, J., Xie, C., Huang, J., **Jiang, Y.**, Miao, Q., & Pu, K. (2018). Semiconducting polymer nanoenzymes with photothermic activity for enhanced cancer therapy. Angewandte Chemie International Edition, 57(15), 3995–3998.
46.	**Jiang, Y.**, Li, J., Zhen, X., Xie, C., & Pu, K. (2018). Dual-peak absorbing semiconducting copolymer nanoparticles for first and second near-infrared window photothermal therapy: A comparative study. Advanced Materials, 30(14), e1705980.
47.	Zhou, J.*, **Jiang, Y.***, Hou, S., Upputuri, P. K., Wu, D., Li, J., Wang, P., Zhen, X., Pramanik, M., Pu, K., & Duan, H. (2018). Compact plasmonic blackbody for cancer theranosis in the near-infrared II window. ACS Nano, 12(3), 2643–2651. (* Co-first author)
48.	Lyu, Y., Zeng, J., **Jiang, Y.**, Zhen, X., Wang, T., Qiu, S., Lou, X., Gao, M., & Pu, K. (2018). Enhancing both biodegradability and efficacy of semiconducting polymer nanoparticles for photoacoustic imaging and photothermal therapy. ACS Nano, 12(2), 1801–1810.
49.	Zhen, X., Xie, C., Jiang, Y, Ai, X., Xing, B., & Pu, K. (2018). Semiconducting photothermal nanoagonist for remote-controlled specific cancer therapy. Nano Letters, 18(2), 1498–1505.
50.	**Jiang, Y.**, Cui, D., Fang, Y., Zhen, X., Upputuri, P. K., Pramanik, M., Ding, D., & Pu, K. (2017). Amphiphilic semiconducting polymer as multifunctional nanocarrier for fluorescence/photoacoustic imaging-guided chemo-photothermal therapy. Biomaterials, 145, 168–177.
51.	**Jiang, Y.**, Upputuri, P. K., Xie, C., Lyu, Y., Zhang, L., Xiong, Q., Pramanik, M., & Pu, K. (2017). Broadband absorbing semiconducting polymer nanoparticles for photoacoustic imaging in second near-infrared window. Nano Letters, 17(8), 4964–4969.
52.	**Jiang, Y.**, & Pu, K. (2017). Advanced photoacoustic imaging applications of near-infrared absorbing organic nanoparticles. Small, 13(30), 1700710.
